---
# tasks file for ansible/roles/app
- name: Launch API container
  docker_container:
    name: simple-api
    image: rihem2002/tp-devops-simple-api

    env:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"

    networks:
      - name: app_network
    restart_policy: always
  vars:
      ansible_python_interpreter: /opt/docker_venv/bin/python