name: Deploy to server

on:
  push:
    branches:
      - main  # ou 'release' si tu préfères

jobs:
  deploy:
    name: Deploy using Ansible
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ansible/inventories/setup.yml ansible/deploy.yml
