name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Cloner le code
      - uses: actions/checkout@v4

      # Étape 2 : Installer JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Étape 3 : Compiler et tester avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml
